spring.application.name=putaway-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/putaway_db
spring.datasource.username=postgres
spring.datasource.password=P17@march

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=putaway-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer