spring.application.name=inbound-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/inbound_db
spring.datasource.username=postgres
spring.datasource.password=P17@march

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true